apiVersion: v1
kind: Service
metadata:
  labels:
    cloudProvider: $DATACENTER
  name: dispatch-$DATACENTER
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: dispatch-$DATACENTER
status:
  loadBalancer: {}
