apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dispatch-$DATACENTER
    cloudProvider: $DATACENTER
  name: dispatch-$DATACENTER
spec:
  containers:
  - env:
    - name: NEW_RELIC_APP_NAME
      value: dispatch-service-$DATACENTER;dispatch-service
    - name: NEW_RELIC_LICENSE_KEY
      value: $NEW_RELIC_LICENSE_KEY
    - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
      value: "true"
    - name: NEW_RELIC_LABELS
      value: datacenter:$DATACENTER;service:dispatch
    - name: AMQP_HOST
      value: rabbitmq-$DATACENTER
    image: $GITHUB_USER/rs-dispatch:$TAG
    name: dispatch
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
