apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    cloudProvider: $DATACENTER
  name: mysql-$DATACENTER
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: mysql-$DATACENTER
status:
  loadBalancer: {}
