apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq-$DATACENTER
    cloudProvider: $DATACENTER
  name: rabbitmq-$DATACENTER
spec:
  containers:
  - image: rabbitmq:3.7-management-alpine
    name: rabbitmq
    resources: {}
  restartPolicy: OnFailure
status: {}
