apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    cloudProvider: $DATACENTER
  name: redis-$DATACENTER
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis-$DATACENTER
status:
  loadBalancer: {}
