apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-$DATACENTER
    cloudProvider: $DATACENTER
  name: user-$DATACENTER
spec:
  containers:
  - env:
    - name: NEW_RELIC_APP_NAME
      value: user-service-$DATACENTER,user-service
    - name: NEW_RELIC_LICENSE_KEY
      value: $NEW_RELIC_LICENSE_KEY
    - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
      value: "true"
    - name: NEW_RELIC_LABELS
      value: datacenter:$DATACENTER;service:user
    - name: MONGO_URL
      value: mongodb://mongodb-$DATACENTER:27017/users
    - name: REDIS_HOST
      value: redis-$DATACENTER
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: K8S_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: K8S_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    image: $GITHUB_USER/rs-user:$TAG
    name: user
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
