apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    cloudProvider: $DATACENTER
  name: mongodb-$DATACENTER
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: mongodb-$DATACENTER
status:
  loadBalancer: {}
