apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: payment-$DATACENTER
    cloudProvider: $DATACENTER
  name: payment-$DATACENTER
spec:
  containers:
  - env:
    - name: NEW_RELIC_APP_NAME
      value: payment-service-$DATACENTER;payment-service
    - name: NEW_RELIC_LICENSE_KEY
      value: $NEW_RELIC_LICENSE_KEY
    - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
      value: "true"
    - name: NEW_RELIC_LABELS
      value: datacenter:$DATACENTER;service:payment
    - name: CART_HOST
      value: cart-$DATACENTER
    - name: USER_HOST
      value: user-$DATACENTER
    - name: AMQP_HOST
      value: rabbitmq-$DATACENTER
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: K8S_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: K8S_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    image: $GITHUB_USER/rs-payment:$TAG
    name: payment
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
