apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    cloudProvider: $DATACENTER
  name: ratings-$DATACENTER
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: ratings-$DATACENTER
status:
  loadBalancer: {}
