apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis-$DATACENTER
    cloudProvider: $DATACENTER
  name: redis-$DATACENTER
spec:
  containers:
  - image: redis:4.0.6
    name: redis
    resources: {}
  restartPolicy: OnFailure
status: {}
