apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: shipping-$DATACENTER
    cloudProvider: $DATACENTER
  name: shipping-$DATACENTER
spec:
  containers:
  - env:
    - name: NEW_RELIC_APP_NAME
      value: shipping-service-$DATACENTER;shipping-service
    - name: NEW_RELIC_LICENSE_KEY
      value: $NEW_RELIC_LICENSE_KEY
    - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
      value: "true"
    - name: NEW_RELIC_LABELS
      value: datacenter:$DATACENTER;service:shipping
    - name: CART_ENDPOINT
      value: cart-$DATACENTER:8080
    - name: DB_HOST
      value: mysql-$DATACENTER
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: K8S_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: K8S_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    image: $GITHUB_USER/rs-shipping:$TAG
    name: shipping
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
