apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    cloudProvider: $DATACENTER
  name: user-$DATACENTER
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: user-$DATACENTER
status:
  loadBalancer: {}
