apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: k8s-nri-rabbitmq-$DATACENTER
    cloudProvider: $DATACENTER
  name: k8s-nri-rabbitmq-$DATACENTER
spec:
  containers:
  - env:
    - name: NRIA_LICENSE_KEY
      value: $NEW_RELIC_LICENSE_KEY
    - name: NRIA_CUSTOM_ATTRIBUTES
      value: '{"clusterName":"$CLUSTER_NAME","datacenter":"$DATACENTER"}'
    image: newrelic/k8s-nri-rabbitmq:latest
    name: k8s-nri-rabbitmq-$DATACENTER
    volumeMounts:
    - name: work-dir
      mountPath: /etc
    resources: {}
  initContainers:
  - name: install
    image: busybox
    env:
    - name: GITHUB_USER
      value: $GITHUB_USER
    - name: GITHUB_REPO
      value: $GITHUB_REPO
    command: ["/bin/sh", "-c", |
      "https://raw.githubusercontent.com/$GITHUB_USER/$GITHUB_REPO/master/newrelic-integrations/k8s-nri-rabbitmq-config.sh"]
    volumeMounts:
    - name: work-dir
      mountPath: "/work-dir"
  volumes:
  - name: work-dir
    emptyDir: {}
  restartPolicy: OnFailure
status: {}
